---
services:
  web:
    container_name: scrutiny-web
    restart: unless-stopped
    image: "ghcr.io/analogj/scrutiny:master-web@sha256:3fd5bcf6fc789632145208cd5b8f94b7e9a467195d6cf31a1b6b7cfdd8e854e2"
    ports:
      - "8091:8080"
    volumes:
      - "./config:/opt/scrutiny/config"
      - "./scrutiny.yaml:/opt/scrutiny/config/scrutiny.yaml"
    healthcheck:
      disable: true
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 20
    #   start_period: 10s
