---
services:
  wazuh-exporter:
    container_name: wazuh-exporter
    environment:
      - "WAZUH_API_HOST=${WAZUH_API_HOST}"
      - "WAZUH_API_PORT=55000"
      - "WAZUH_API_USERNAME=${WAZUH_API_USERNAME}"
      - "WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD}"
      - "EXPORTER_PORT=5008"
    image: docker.io/kennyopennix/wazuh-exporter:latest
    network_mode: host
    restart: unless-stopped
    labels:
      io.containers.autoupdate: "registry"
