---
services:
  hawser:
    image: ghcr.io/finsys/hawser:0.2.45
    container_name: hawser-for-dockhand
    volumes:
      - /run/user/${USER_ID-1000}/podman/podman.sock:/var/run/docker.sock:z
      - hawser_stacks:/data/stacks
    ports:
      - "2376:2376"
    environment:
      - STACKS_DIR=/data/stacks
      - PUID=${USER_ID-1000}
      - PGID=${GROUP_ID-1000}

volumes:
  hawser_stacks:
