services:
  frontend:
    image: ghcr.io/adminsyspro/proxcenter-frontend:v1.4.9
    container_name: proxcenter
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - proxcenter_data:/app/data
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "curl", "-sf", "http://localhost:3000/api/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 12
    #   start_period: 30s

volumes:
  proxcenter_data:
    external: true
