---
services:
  postgres-exporter:
    network_mode: host
    container_name: postgres-exporter
    environment:
      - "DATA_SOURCE_URI=${DATA_SOURCE_URI}"
      - "DATA_SOURCE_USER=${DATA_SOURCE_USER}"
      - "DATA_SOURCE_PASS=${DATA_SOURCE_PASS}"
    image: quay.io/prometheuscommunity/postgres-exporter:v0.19.1
    restart: unless-stopped
    labels:
      io.containers.autoupdate: "registry"
