---
services:
  hawser:
    image: ghcr.io/finsys/hawser:0.2.45
    container_name: hawser-for-dockhand
    volumes:
      - /run/user/${USER_ID-1000}/podman/podman.sock:/var/run/docker.sock:z
      - hawser_stacks:/data/stacks
    security_opt:
      - apparmor:unconfined
      - "label=type:container_runtime_t"
    environment:
      - STACKS_DIR=/data/stacks
      - PUID=${USER_ID-1000}
      - PGID=${GROUP_ID-1000}
      - DOCKHAND_SERVER_URL=wss://pihole2.tailebee.ts.net:3005/api/hawser/connect
      - TOKEN=${HAWSER_TOKEN}

volumes:
  hawser_stacks:
