---
services:
  rackpeek:
    image: docker.io/aptacode/rackpeek:v2.0.0
    container_name: rackpeek
    ports:
      - "8080:8080"
    volumes:
      - rackpeek-config:/app/config
    restart: unless-stopped
    labels:
      io.containers.autoupdate: "registry"

volumes:
  rackpeek-config:
